import Head from "next/head";
import MainLayout from "../components/layouts/main-layout";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        animate={{ scale: 0.5, origin: 0 }}
        transition={{ duration: 2 }}
        className="text-3xl underline font-bold w-32"
      >
        سلام عبداللهیان
      </motion.div>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>;
};
