import Head from "next/head";
import MainLayout from "../components/layouts/main-layout";
import Fullpage, {
  FullPageSections,
  FullpageSection,
} from "@ap.cx/react-fullpage";

export default function Home() {
  const SectionStyle = {
    height: "100vh",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fullpage>
        <FullPageSections>
          <FullpageSection>
            <h1>صفحه اول</h1>
          </FullpageSection>
          <FullpageSection>
            <h1>صفحه دوم</h1>
          </FullpageSection>
          <FullpageSection>
            <h1>صفحه سوم</h1>
          </FullpageSection>
        </FullPageSections>
      </Fullpage>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>;
};
